# coding: utf-8

"""
    Stack Overflow Object Detection API

    API that fetches the top 10 users from the Stack Overflow Users API, reads their profile images, and uses an open-source object detection model to detect specified objects in those images.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.users_post500_response import UsersPost500Response

class TestUsersPost500Response(unittest.TestCase):
    """UsersPost500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersPost500Response:
        """Test UsersPost500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersPost500Response`
        """
        model = UsersPost500Response()
        if include_optional:
            return UsersPost500Response(
                error = 'Internal Server Error'
            )
        else:
            return UsersPost500Response(
        )
        """

    def testUsersPost500Response(self):
        """Test UsersPost500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
